using IT_ELECTIVE_2_BSIT31E1_PREFINAL_EXAM_Osiana_Raiza.Models;
using Microsoft.AspNetCore.Mvc;

namespace IT_ELECTIVE_2_BSIT31E1_PREFINAL_EXAM_Osiana_Raiza.Controllers;

public class ExamController : Controller
{
    private static readonly List<ExamItem> ExamQuestions =
    [
        new() { Id = 1, Question = "What is the main problem solved by using a database instead of an in-memory collection?", Options = ["A. It makes C# code shorter", "B. It prevents the application from restarting", "C. It allows data to persist after the application stops", "D. It removes the need for MVC"], CorrectAnswer = "C", Explanation = "Databases allow data persistence after the application stops." },
        new() { Id = 2, Question = "Which approach is being used when an existing database is used to generate EF Core entity classes?", Options = ["A. Code-First", "B. Database-First", "C. Model-First", "D. Controller-First"], CorrectAnswer = "B", Explanation = "Generating entities from existing schemas is the Database-First approach." },
        new() { Id = 3, Question = "What is the primary purpose of Entity Framework Core?", Options = ["A. To create HTML pages automatically", "B. To replace the MVC Controller", "C. To map objects in code to relational database data", "D. To replace the C# compiler"], CorrectAnswer = "C", Explanation = "EF Core acts as an ORM mapping code objects to relational databases." },
        new() { Id = 4, Question = "Which EF Core component is primarily responsible for communicating with the database?", Options = ["A. DbContext", "B. DbSetView", "C. ControllerContext", "D. RazorContext"], CorrectAnswer = "A", Explanation = "DbContext manages database connections, querying, and updates." },
        new() { Id = 5, Question = "What does the command dotnet ef dbcontext scaffold do?", Options = ["A. Deletes the database", "B. Creates a new MVC project", "C. Generates EF Core models and a DbContext from an existing database", "D. Starts the MVC application"], CorrectAnswer = "C", Explanation = "Scaffolding generates models and DbContext from an existing database." },
        new() { Id = 6, Question = "Where is a database connection string commonly stored in an ASP.NET Core MVC application?", Options = ["A. Program.cs only", "B. appsettings.json", "C. Index.cshtml", "D. Student.cs"], CorrectAnswer = "B", Explanation = "Connection strings are typically configured inside appsettings.json." },
        new() { Id = 7, Question = "A Student belongs to exactly one Section, while a Section can contain many students. What type of relationship is this?", Options = ["A. One-to-One", "B. One-to-Many", "C. Many-to-Many", "D. Many-to-One only"], CorrectAnswer = "B", Explanation = "One section having multiple students represents a One-to-Many relationship." },
        new() { Id = 8, Question = "In the following example, what is SectionId? public int SectionId { get; set; }", Options = ["A. Primary key of Student", "B. Foreign key referencing Section", "C. Navigation property", "D. Database connection string"], CorrectAnswer = "B", Explanation = "SectionId acts as the Foreign Key linking to the Section entity." },
        new() { Id = 9, Question = "What is the purpose of a navigation property such as public Section Section { get; set; }?", Options = ["A. It stores the database password", "B. It represents a relationship to another entity", "C. It creates a new database", "D. It validates the student's name"], CorrectAnswer = "B", Explanation = "Navigation properties define entity relationships in code." },
        new() { Id = 10, Question = "What does .Include() generally allow EF Core to do?", Options = ["A. Delete the Section table", "B. Load related Section data together with Students", "C. Create a new Student", "D. Validate Student input"], CorrectAnswer = "B", Explanation = ".Include() eagerly loads related navigational data." },
        new() { Id = 11, Question = "Why might a ViewModel be used when displaying Student and Section information?", Options = ["A. To replace the database", "B. To combine or shape the data specifically needed by the view", "C. To automatically create database tables", "D. To prevent controllers from using LINQ"], CorrectAnswer = "B", Explanation = "ViewModels format and combine data tailored specifically for views." },
        new() { Id = 12, Question = "What is the main benefit of Include(s => s.Section)?", Options = ["A. It loads the related Section navigation property", "B. It creates a Section object manually", "C. It removes the foreign key", "D. It prevents the query from accessing the database"], CorrectAnswer = "A", Explanation = "It specifically loads the Section navigational relationship." },
        new() { Id = 13, Question = "Which type of validation occurs in the browser before a request is sent to the server?", Options = ["A. Database-level validation", "B. Client-side validation", "C. Server-side validation", "D. EF Core migration validation"], CorrectAnswer = "B", Explanation = "Validation inside the user's browser is client-side validation." },
        new() { Id = 14, Question = "Why is server-side validation still necessary if client-side validation exists?", Options = ["A. Client-side validation can be bypassed", "B. Client-side validation automatically modifies the database", "C. Server-side validation only works with SQLite", "D. Client-side validation cannot display messages"], CorrectAnswer = "A", Explanation = "Client-side validation can be bypassed or disabled by users." },
        new() { Id = 15, Question = "A school requires every student to have a unique Student Number. Which rule best represents this requirement?", Options = ["A. Student Number should always be nullable", "B. Student Number should be unique", "C. Student Number should always be the same", "D. Student Number should contain only spaces"], CorrectAnswer = "B", Explanation = "Uniqueness rules prevent duplicate records." },
        new() { Id = 16, Question = "Which is the best reason for having a database-level unique constraint on StudentNumber?", Options = ["A. It protects data integrity even if application-level validation is bypassed", "B. It makes Razor Views render faster", "C. It removes the need for a Controller", "D. It automatically creates a ViewModel"], CorrectAnswer = "A", Explanation = "Database constraints enforce data integrity at the lowest level." },
        new() { Id = 17, Question = "What is the purpose of a try...catch block in a controller?", Options = ["A. To create navigation properties", "B. To catch and handle exceptions that may occur during execution", "C. To generate database tables", "D. To perform client-side validation"], CorrectAnswer = "B", Explanation = "try...catch blocks handle unexpected runtime errors gracefully." },
        new() { Id = 18, Question = "Which middleware is commonly used in ASP.NET Core for centralized exception handling?", Options = ["A. UseDatabase()", "B. UseExceptionHandler()", "C. UseValidationHandler()", "D. UseMvcDatabase()"], CorrectAnswer = "B", Explanation = "UseExceptionHandler() provides centralized error handling." },
        new() { Id = 19, Question = "A user requests /Student/999, but Student 999 does not exist. What would be the most appropriate response?", Options = ["A. Display the student's information anyway", "B. Display a Not Found (404) response/page", "C. Delete Student 999", "D. Create Student 999 automatically"], CorrectAnswer = "B", Explanation = "A missing resource should return HTTP 404 Not Found." },
        new() { Id = 20, Question = "The application attempts to assign the same student to Section A again. What is the primary concern?", Options = ["A. Data integrity", "B. HTML formatting", "C. CSS inheritance", "D. Razor syntax"], CorrectAnswer = "A", Explanation = "Duplicate entries compromise data integrity." }
    ];

    public IActionResult Index() => View(ExamQuestions);
}